const payload=JSON.parse(document.getElementById('budget-price-data').textContent);
const keyMap={sporthall:'Sporthall',simhall:'Simhall',konferens:'Konferens',restaurang:'Restaurang',gym:'Gym'};
const DB=Object.fromEntries(Object.entries(payload.areas).map(([slug,area])=>[keyMap[slug],area.groups]));
const fmt=new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:0});
const meta={
 Sporthall:{slug:'sporthall',label:'Sporthall',title:'Budgetkalkylator för sporthallsteknik',lead:'Ljud, styrning, hörslinga, Auracast, STI, mikrofoner, läktare, LED-vägg och entreprenadkrav.',note:'Sporthall använder de befintliga startvärdena från HTML-kalkylatorn.',test:false},
 Simhall:{slug:'simhall',label:'Simhall',title:'Budgetkalkylator för simhallsteknik',lead:'Testa basljud, styrning, tillgänglighet, STI, mikrofoner, extra zoner, informationsskärm och projektor.',note:'TESTSTARTVÄRDEN från Excel. Byt nivåerna innan skarp publicering.',test:true},
 Konferens:{slug:'konferens',label:'Konferens',title:'Budgetkalkylator för konferensteknik',lead:'Testa rumstyp, BYOD eller Teams Room, bild, ljud, kamera, styrning, mikrofoner och tillgänglighet.',note:'TESTSTARTVÄRDEN från Excel. Byt nivåerna innan skarp publicering.',test:true},
 Restaurang:{slug:'restaurang',label:'Restaurang',title:'Budgetkalkylator för restaurangteknik',lead:'Testa bakgrundsljud, zonstyrning, eventläge, uteservering, mikrofoner, skärm och dokumentation.',note:'TESTSTARTVÄRDEN från Excel. Byt nivåerna innan skarp publicering.',test:true},
 Gym:{slug:'gym',label:'Gym',title:'Budgetkalkylator för gymteknik',lead:'Testa zonstyrt ljud, gruppträning, headset, musikanslutning, utrop, skärm och extra ljudzoner.',note:'TESTSTARTVÄRDEN från Excel. Byt nivåerna innan skarp publicering.',test:true}
};
const configs={
 Sporthall:[
  {kind:'choice',group:'hallType',title:'Halltyp och grundlogik',desc:'Välj den halltyp som ligger närmast projektet.',default:'dividable'},
  {kind:'choice',group:'basePackage',title:'Basljudpaket för sporthall',desc:'Huvudljud och systemlogik.',default:'dsp'},
  {kind:'choice',group:'standsSound',title:'Ljud mot läktare',desc:'Separat ljud mot publikplats.',default:'none'},
  {kind:'choice',group:'control',title:'Styrning',desc:'Vridreglage eller touchstyrning.',default:'touch'},
  {kind:'quantity',group:'unit',keys:['handMic','headset','bluetooth'],title:'Mikrofoner, headset och Bluetooth',defaults:{handMic:2,headset:0,bluetooth:2}},
  {kind:'choice',group:'loopPlan',title:'Hörslinga på planen',desc:'Standardplan eller separat offert.',default:'none'},
  {kind:'toggleChoice',group:'auracast',title:'Auracast',desc:'Komplement för publika ytor och läktare.',default:'none'},
  {kind:'choice',group:'sti',title:'STI och inmätning',desc:'Välj krav på taluppfattbarhet.',default:'none'},
  {kind:'quantity',group:'unit',keys:['zoneSmall','zoneMedium','zoneLarge'],title:'Extra ljudzoner',defaults:{zoneSmall:0,zoneMedium:0,zoneLarge:0}},
  {kind:'sportExtra',title:'LED-vägg, läktare och entreprenadkrav'}
 ],
 Simhall:[
  {kind:'choice',group:'facilityType',title:'Simhallstyp',desc:'Grundlogik för anläggningen.',default:'standard'},
  {kind:'choice',group:'basePackage',title:'Basljud simhall',desc:'Grundpaket eller fler zoner med DSP.',default:'standard'},
  {kind:'choice',group:'control',title:'Styrning',desc:'Enkel styrning eller touch.',default:'knob'},
  {kind:'choice',group:'accessibility',title:'Tillgänglighet',desc:'Hörslinga eller Auracast.',default:'none'},
  {kind:'choice',group:'sti',title:'STI och inmätning',desc:'Taluppfattbarhet där det behövs.',default:'none'},
  {kind:'quantity',group:'unit',keys:['handMic','headset','bluetooth'],title:'Mikrofoner och anslutning',defaults:{}},
  {kind:'quantity',group:'unit',keys:['zoneSmall','zoneMedium','zoneLarge'],title:'Extra ljudzoner',defaults:{}},
  {kind:'multiToggle',group:'display',title:'Bild och information',desc:'Lägg till skärm och/eller projektor.',keys:['infoScreen','projector']},
  {kind:'checks',group:'checks',title:'Dokumentation och krav',keys:['documentation','fireAlarm','quoteSystems','warranty5']}
 ],
 Konferens:[
  {kind:'choice',group:'roomType',title:'Rumstyp',desc:'Storlek och grundlogik.',default:'small'},
  {kind:'choice',group:'basePackage',title:'Konferensplattform',desc:'BYOD eller Teams Room.',default:'byod'},
  {kind:'choice',group:'display',title:'Bildvisning',desc:'En eller två bildytor.',default:'single'},
  {kind:'choice',group:'audio',title:'Konferensljud',desc:'Grundläggande eller utökad AEC/lösning.',default:'ceiling'},
  {kind:'choice',group:'control',title:'Styrning',desc:'Enkel eller touch.',default:'simple'},
  {kind:'choice',group:'camera',title:'Kamera',desc:'Standard eller utökad funktion.',default:'standard'},
  {kind:'quantity',group:'unit',keys:['wirelessMic','ceilingMic'],title:'Mikrofoner',defaults:{}},
  {kind:'choice',group:'accessibility',title:'Tillgänglighet',desc:'Hörslinga eller Auracast.',default:'none'},
  {kind:'checks',group:'checks',title:'Dokumentation och garanti',keys:['documentation','warranty5']}
 ],
 Restaurang:[
  {kind:'choice',group:'venueType',title:'Lokaltyp',desc:'Storlek och grundlogik.',default:'small'},
  {kind:'choice',group:'basePackage',title:'Ljudpaket',desc:'Bakgrundsljud, flera zoner eller event/fest.',default:'background'},
  {kind:'choice',group:'control',title:'Styrning',desc:'Vridreglage eller touch/app.',default:'knob'},
  {kind:'quantity',group:'unit',keys:['zoneSmall','zoneMedium','zoneLarge','outdoorZone'],title:'Ljudzoner',defaults:{}},
  {kind:'quantity',group:'unit',keys:['bluetooth','handMic'],title:'Anslutning och mikrofon',defaults:{}},
  {kind:'choice',group:'display',title:'Digital signage/skärm',desc:'Lägg till skärm/signage.',default:'none'},
  {kind:'choice',group:'event',title:'DJ-/eventanslutning',desc:'Lägg till inkopplingspunkt och signalväg.',default:'none'},
  {kind:'checks',group:'checks',title:'Dokumentation och garanti',keys:['documentation','warranty5']}
 ],
 Gym:[
  {kind:'choice',group:'facilityType',title:'Gymtyp',desc:'Storlek och grundlogik.',default:'small'},
  {kind:'choice',group:'basePackage',title:'Gym-ljud',desc:'Grundpaket eller fler zoner.',default:'gym'},
  {kind:'choice',group:'groupTraining',title:'Gruppträningssal',desc:'Lägg till gruppträningslösning.',default:'none'},
  {kind:'choice',group:'control',title:'Styrning',desc:'Enkel zonstyrning eller touch/app.',default:'knob'},
  {kind:'quantity',group:'unit',keys:['headset','bluetooth','handMic'],title:'Instruktör och anslutning',defaults:{}},
  {kind:'quantity',group:'unit',keys:['zoneSmall','zoneMedium','zoneLarge'],title:'Extra ljudzoner',defaults:{}},
  {kind:'choice',group:'display',title:'Informationsskärm',desc:'Lägg till skärm/information.',default:'none'},
  {kind:'choice',group:'announcement',title:'Utrop',desc:'Lägg till utropsfunktion.',default:'none'},
  {kind:'checks',group:'checks',title:'Dokumentation och garanti',keys:['documentation','warranty5']}
 ]
};
let active='Sporthall';
const states={};
function areaState(area){if(states[area])return states[area];const s={selected:{},qty:{},checks:{},sport:{ledWidth:0,ledHeight:0,ledPitch:'none',standsCount:0,standRows:[],contract:'none',install:'none'}};configs[area].forEach(c=>{if(c.default)s.selected[c.group]=c.default;if(c.kind==='quantity')c.keys.forEach(k=>s.qty[k]=(c.defaults&&c.defaults[k])||0);if(c.kind==='checks')c.keys.forEach(k=>s.checks[k]=false);if(c.kind==='multiToggle')c.keys.forEach(k=>s.checks[c.group+':'+k]=false)});states[area]=s;return s}
function item(area,group,key){return DB[area]?.[group]?.[key]}
function labelFor(key,it){const map={handMic:'Trådlös handmikrofon',headset:'Trådlöst headset',bluetooth:'Bluetooth-mottagare',zoneSmall:'Zon 20–50 m²',zoneMedium:'Zon 50–100 m²',zoneLarge:'Zon 100–200 m²',wirelessMic:'Trådlös mikrofon',ceilingMic:'Takmikrofon',outdoorZone:'Uteservering/utomhuszon'};return map[key]||it?.label||key}
function optionName(group,key,it){const names={simple:'Enkel / liten',dividable:'Delbar A/B-hall',stands:'Hall med läktare',sti:'STI-krav/eventläge',dsp:'DSP / fler zoner',none:'Ingen',standard:'Standard',custom:'Annan storlek',basic:'Auracast','050':'STI 0,50','060':'STI 0,60','070':'STI 0,70 / offert',knob:'Vridreglage',touch:'Touchstyrning',multi:'Flera bassänger/zoner',loopStandard:'Hörslinga',auracast:'Auracast',small:'Mindre',medium:'Mellan',large:'Större',byod:'BYOD',teams:'Teams Room',single:'En bildyta',dual:'Dubbla bildytor',ceiling:'Grundläggande',premium:'Utökad/AEC',tracking:'Utökad tracking',loop:'Hörslinga',background:'Bakgrundsljud',multizone:'Flera zoner',event:'Event/fest',gym:'Grundpaket gym'};if(group==='standsSound'&&key==='eight12')return 'Läktarljud';if(group==='basePackage'&&key==='simple')return 'Enkel hall med mixer';if(group==='groupTraining'&&key==='standard')return 'Standard gruppträning';if(group==='groupTraining'&&key==='premium')return 'Utökad gruppträning';if(group==='display'&&key==='infoScreen')return 'Informationsskärm';if(group==='display'&&key==='projector')return 'Projektor / bild';if(group==='display'&&key==='signage')return 'Digital signage/skärm';if(group==='announcement'&&key==='basic')return 'Utrop';if(group==='event'&&key==='djInput')return 'DJ-/eventanslutning';return names[key]||it?.label||key}
function renderTypes(){const g=document.getElementById('typeGrid');g.innerHTML=Object.keys(meta).map(a=>`<button class="type-card ${a===active?'is-active':''}" data-area="${a}" type="button"><small>${a===active?'Vald':'Välj'}</small><h3>${meta[a].label}</h3><p>${meta[a].lead.split('.')[0]}.</p>${meta[a].test?'<span class="testflag">TESTSTARTVÄRDEN</span>':''}</button>`).join('');g.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>switchArea(b.dataset.area))}
function switchArea(a){active=a;renderTypes();renderArea()}
function panelShell(i,title,desc,body){return `<section class="calc-panel"><div class="calc-panel-header"><div class="panel-icon">${String(i+1).padStart(2,'0')}</div><div><h3>${title}</h3><p>${desc||''}</p></div></div><div class="calc-panel-body">${body}</div></section>`}
function renderArea(){const m=meta[active],s=areaState(active);document.getElementById('typeMessage').textContent=`Valt område: ${m.label}${m.test?' – teststartvärden':''}.`;document.getElementById('areaEyebrow').textContent=m.label;document.getElementById('areaTitle').textContent=m.title;document.getElementById('areaLead').textContent=m.lead;document.getElementById('areaNote').innerHTML=(m.test?'<strong>TEST:</strong> ':'')+m.note;document.getElementById('summaryIntro').textContent=`Budgetunderlag för ${m.label.toLowerCase()}. Belopp exklusive moms.`;let html=m.test?'<div class="test-note">Det här området använder TESTSTARTVÄRDEN från Excel. Flödet är testbart nu, men priserna ska ersättas/granskas innan publicering.</div>':'';configs[active].forEach((c,i)=>{if(c.kind==='choice'||c.kind==='toggleChoice'){const opts=DB[active][c.group]||{};let body='<div class="choice-grid">'+Object.entries(opts).map(([k,it])=>`<button class="tile-option ${s.selected[c.group]===k?'is-selected':''}" data-choice="${c.group}" data-key="${k}" type="button"><strong>${optionName(c.group,k,it)}</strong><span>${it.note||it.label}</span><b>${it.quote?'Offert':fmt.format(it.price||0)}</b></button>`).join('')+'</div>';html+=panelShell(i,c.title,c.desc,body)}else if(c.kind==='quantity'){let body='<div class="quantity-list">'+c.keys.map(k=>{const it=item(active,c.group,k);return `<div class="quantity-row"><div><strong>${labelFor(k,it)}</strong><span>${it?.note||''} · ${fmt.format(it?.price||0)} / st</span></div><div class="stepper"><button data-step="${k}" data-dir="-1" type="button">−</button><input data-qty="${k}" type="number" min="0" max="20" value="${s.qty[k]||0}"><button data-step="${k}" data-dir="1" type="button">+</button></div></div>`}).join('')+'</div>';html+=panelShell(i,c.title,'Ange antal.',body)}else if(c.kind==='multiToggle'){let body='<div class="check-grid">'+c.keys.map(k=>{const it=item(active,c.group,k),id=c.group+':'+k;return `<label class="check-option"><input type="checkbox" data-multi="${id}" ${s.checks[id]?'checked':''}><span><strong>${optionName(c.group,k,it)}</strong><span>${it.note||''} · ${fmt.format(it.price||0)}</span></span></label>`}).join('')+'</div>';html+=panelShell(i,c.title,c.desc,body)}else if(c.kind==='checks'){let body='<div class="check-grid">'+c.keys.map(k=>{const it=item(active,c.group,k);return `<label class="check-option"><input type="checkbox" data-check="${k}" ${s.checks[k]?'checked':''}><span><strong>${checkName(k,it)}</strong><span>${it.note||''}${it.type==='Procent'?'':' · '+(it.quote?'Offert':fmt.format(it.price||0))}</span></span></label>`}).join('')+'</div>';html+=panelShell(i,c.title,'Val som påverkar kalkyl eller underlag.',body)}else if(c.kind==='sportExtra'){html+=panelShell(i,c.title,'Specialdelar från den ursprungliga sporthallskalkylen.',sportExtraHtml(s))}});document.getElementById('calcStack').innerHTML=html;bindControls();calculate()}
function checkName(k,it){return {documentation:'Relationshandling och dokumentation',fireAlarm:'Brandlarm tystar ljud',quoteSystems:'Rastsignal / talat utrymningslarm',warranty5:'5 års garantitid'}[k]||it?.label||k}
function sportExtraHtml(s){return `<div class="form-grid"><div class="form-field"><label>LED bredd (m)</label><input id="ledWidth" type="number" min="0" step="0.1" value="${s.sport.ledWidth}"></div><div class="form-field"><label>LED höjd (m)</label><input id="ledHeight" type="number" min="0" step="0.1" value="${s.sport.ledHeight}"></div><div class="form-field"><label>Pixelpitch</label><select id="ledPitch"><option value="none">Ingen LED-vägg</option><option value="p25">P2.5</option><option value="p39">P3.9</option><option value="p49">P4.9</option><option value="quote">Special/offert</option></select></div></div><div style="height:18px"></div><div class="form-grid"><div class="form-field"><label>Antal läktare</label><select id="standsCount"><option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></div><div class="form-field"><label>Entreprenadform</label><select id="contract"><option value="none">Ej angivet</option><option value="ab04">AB 04</option><option value="abt06">ABT 06</option></select></div><div class="form-field"><label>Installation</label><select id="install"><option value="none">Ej angivet</option><option value="avabInstall">AVAB installerar</option><option value="electricianInstall">Elektriker installerar, AVAB drifts?tter</option></select></div></div><div id="standsRows" style="display:grid;gap:12px;margin-top:16px"></div><div class="check-grid" style="margin-top:16px">${['documentation','fireAlarm','quoteSystems','warranty5'].map(k=>{const it=item('Sporthall','checks',k);return `<label class="check-option"><input type="checkbox" data-check="${k}" ${s.checks[k]?'checked':''}><span><strong>${checkName(k,it)}</strong><span>${it.note||''}</span></span></label>`}).join('')}</div>`}
function bindControls(){const s=areaState(active);document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const g=b.dataset.choice,k=b.dataset.key;if(configs[active].find(c=>c.group===g&&c.kind==='toggleChoice')&&s.selected[g]===k)s.selected[g]='none';else s.selected[g]=k;renderArea()});document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const k=b.dataset.step;s.qty[k]=Math.max(0,Math.min(20,(s.qty[k]||0)+Number(b.dataset.dir)));renderArea()});document.querySelectorAll('[data-qty]').forEach(inp=>inp.oninput=()=>{s.qty[inp.dataset.qty]=Math.max(0,Number(inp.value||0));calculate()});document.querySelectorAll('[data-check]').forEach(inp=>inp.onchange=()=>{s.checks[inp.dataset.check]=inp.checked;calculate()});document.querySelectorAll('[data-multi]').forEach(inp=>inp.onchange=()=>{s.checks[inp.dataset.multi]=inp.checked;calculate()});if(active==='Sporthall'){const ids=['ledWidth','ledHeight','ledPitch','standsCount','contract','install'];ids.forEach(id=>{const el=document.getElementById(id);if(!el)return;if(id==='ledPitch')el.value=s.sport.ledPitch;if(id==='standsCount')el.value=s.sport.standsCount;if(id==='contract')el.value=s.sport.contract;if(id==='install')el.value=s.sport.install;el.onchange=el.oninput=()=>{s.sport[id]=['ledWidth','ledHeight','standsCount'].includes(id)?Number(el.value||0):el.value;if(id==='standsCount')renderArea();else calculate()}});renderStandRows()}}
function renderStandRows(){if(active!=='Sporthall')return;const s=areaState(active),box=document.getElementById('standsRows');if(!box)return;while(s.sport.standRows.length<s.sport.standsCount)s.sport.standRows.push({size:'medium',access:'loop'});s.sport.standRows=s.sport.standRows.slice(0,s.sport.standsCount);box.innerHTML=s.sport.standRows.map((r,i)=>`<div class="form-grid" style="padding:14px;background:var(--light);border-radius:var(--rs);border:1px solid var(--b)"><div><strong>Läktare ${i+1}</strong></div><div class="form-field"><label>Storlek</label><select data-stand-size="${i}"><option value="small">8–20 m²</option><option value="medium">20–40 m²</option><option value="large">40–80 m²</option><option value="quote">Större än 80 m²</option></select></div><div class="form-field"><label>Tillgänglighet</label><select data-stand-access="${i}"><option value="none">Ingen</option><option value="loop">Hörslinga</option><option value="auracast">Auracast</option><option value="both">Båda</option></select></div></div>`).join('');box.querySelectorAll('[data-stand-size]').forEach(el=>{const i=Number(el.dataset.standSize);el.value=s.sport.standRows[i].size;el.onchange=()=>{s.sport.standRows[i].size=el.value;calculate()}});box.querySelectorAll('[data-stand-access]').forEach(el=>{const i=Number(el.dataset.standAccess);el.value=s.sport.standRows[i].access;el.onchange=()=>{s.sport.standRows[i].access=el.value;calculate()}})}
function add(map,it,mult=1,note=''){if(!it)return;const label=it.label||'Post',id=label;let g=map.get(id);if(!g){g={label,price:0,hours:0,quote:false,notes:[]};map.set(id,g)}g.price+=(it.price||0)*mult;g.hours+=(it.hours||0)*mult;g.quote=g.quote||!!it.quote;if(note||it.note)g.notes.push(note||it.note)}
function calculate(){const s=areaState(active),map=new Map();configs[active].forEach(c=>{if(c.kind==='choice'||c.kind==='toggleChoice'){add(map,item(active,c.group,s.selected[c.group]))}else if(c.kind==='quantity'){c.keys.forEach(k=>{const n=s.qty[k]||0;if(n)add(map,item(active,c.group,k),n,`${n} st ${labelFor(k,item(active,c.group,k)).toLowerCase()}.`)})}else if(c.kind==='multiToggle'){c.keys.forEach(k=>{if(s.checks[c.group+':'+k])add(map,item(active,c.group,k))})}else if(c.kind==='checks'){c.keys.filter(k=>k!=='warranty5').forEach(k=>{if(s.checks[k])add(map,item(active,c.group,k))})}});if(active==='Sporthall')sportCalc(map,s);let subtotal=[...map.values()].reduce((a,g)=>a+g.price,0);if(s.checks.warranty5&&subtotal){add(map,{label:'Garanti och materialhantering',price:Math.round(subtotal*payload.meta.warrantyRate),hours:0,note:'5 års garantitid – 10 % testregel.'})}const groups=[...map.values()].filter(g=>g.price||g.hours||g.quote||g.notes.length);const total=Math.round(groups.reduce((a,g)=>a+g.price,0));const hours=groups.reduce((a,g)=>a+g.hours,0);document.getElementById('totalPrice').textContent=fmt.format(total);document.getElementById('mobileTotal').textContent=fmt.format(total);document.getElementById('hoursText').textContent=hours?`Uppskattad projektering/installation: ca ${Math.round(hours)} timmar.`:'Ingen tidsuppskattning i valda poster.';document.getElementById('summaryList').innerHTML=groups.length?groups.map(g=>`<li><span>${g.label}${g.notes.length?`<em>${[...new Set(g.notes)].slice(0,2).join(' ')}</em>`:''}</span><b>${g.quote&&!g.price?'Offert':fmt.format(Math.round(g.price))+(g.quote?' + offert':'')}</b></li>`).join(''):'<li><span>Välj funktioner för att bygga kalkylen.</span><b>0 kr</b></li>';window.__calc={groups,total,hours}}
function sportCalc(map,s){const p=DB.Sporthall;if(s.sport.contract!=='none')add(map,p.checks[s.sport.contract]);if(s.sport.install!=='none')add(map,p.checks[s.sport.install]);s.sport.standRows.forEach(r=>{const base=p.stands[r.size],acc=p.standAccess[r.access];if(!base)return;if(base.quote){add(map,{label:'Läktare och tillgänglighet',price:0,hours:0,quote:true,note:'Större läktare kräver separat offert.'});return}add(map,{label:'Läktare och tillgänglighet',price:Math.round(base.price*acc.multiplier+acc.extra),hours:Math.round(base.hours*acc.hourMultiplier),note:acc.note})});const led=p.ledPitch[s.sport.ledPitch];if(s.sport.ledPitch!=='none'){if(led.quote)add(map,{label:'LED-vägg',price:0,hours:0,quote:true,note:'Speciallösning kräver offert.'});else if(s.sport.ledWidth>0&&s.sport.ledHeight>0){const sqm=s.sport.ledWidth*s.sport.ledHeight;add(map,{label:'LED-vägg',price:Math.round(sqm*led.sqm+led.start),hours:Math.round(10+sqm*1.5),note:`${sqm.toFixed(1).replace('.',',')} m².`})}}['documentation','fireAlarm','quoteSystems'].forEach(k=>{if(s.checks[k])add(map,p.checks[k])})}
function leadText(){const c=window.__calc||{groups:[],total:0,hours:0};return [`AVAB budgetkalkylator – ${active}`,`Företag: ${document.getElementById('company').value||'-'}`,`Namn: ${document.getElementById('contactName').value||'-'}`,`Projekt: ${document.getElementById('projectName').value||'-'}`,`Projektläge: ${document.getElementById('stage').value||'-'}`,'','Valda funktionsdelar:',...c.groups.map(g=>`- ${g.label}: ${g.quote&&!g.price?'Offert':fmt.format(Math.round(g.price))}`),'',`Budget exkl. moms: ${fmt.format(c.total)}`,`Uppskattad tid: ca ${Math.round(c.hours)} h`,meta[active].test?'OBS: TESTSTARTVÄRDEN – granskas före publicering.':''].filter(Boolean).join('\n')}
function showStatus(t){const e=document.getElementById('status');e.textContent=t;e.classList.add('show')}
document.getElementById('leadForm').onsubmit=e=>{e.preventDefault();const c=window.__calc||{groups:[],total:0,hours:0};const logoSrc=document.querySelector('.site-nav .brand img')?.src||'';const w=window.open('','_blank');w.document.write(`<!doctype html><html lang="sv"><head><meta charset="utf-8"><title>Budgetunderlag ${active}</title><style>body{font-family:Arial,sans-serif;margin:40px;color:#282E29}.print-logo{display:block;width:154px;height:auto;margin:0 0 32px}h1{font-size:28px}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}td:last-child,th:last-child{text-align:right}.total{margin-top:20px;padding:18px;background:#282E29;color:white}.total strong{display:block;color:#8FC025;font-size:26px}.test{padding:12px;background:#fff4cc;border:1px solid #e5cb65;margin:16px 0}</style></head><body>${logoSrc?`<img class="print-logo" src="${esc(logoSrc)}" alt="AVAB">`:''}<h1>Budgetunderlag – ${active}</h1>${meta[active].test?'<div class="test">TESTSTARTVÄRDEN – inte skarpa priser.</div>':''}<p><strong>Företag:</strong> ${esc(document.getElementById('company').value||'-')}<br><strong>Namn:</strong> ${esc(document.getElementById('contactName').value||'-')}<br><strong>Projekt:</strong> ${esc(document.getElementById('projectName').value||'-')}<br><strong>Projektläge:</strong> ${esc(document.getElementById('stage').value||'-')}</p><table><thead><tr><th>Funktionsdel</th><th>Budget</th></tr></thead><tbody>${c.groups.map(g=>`<tr><td>${esc(g.label)}</td><td>${g.quote&&!g.price?'Offert':fmt.format(Math.round(g.price))}</td></tr>`).join('')}</tbody></table><div class="total">Budgetindikation exkl. moms<strong>${fmt.format(c.total)}</strong>Uppskattad tid: ca ${Math.round(c.hours)} h</div><p>Detta är ett budgetunderlag, inte en bindande offert.</p><script>window.onload=()=>setTimeout(()=>window.print(),200)<\/script></body></html>`);w.document.close();showStatus('Utskriftsvyn öppnades. Välj Spara som PDF om du vill.')};
document.getElementById('copyCalc').onclick=async()=>{const t=leadText();try{await navigator.clipboard.writeText(t);showStatus('Kalkylen är kopierad.')}catch{showStatus(t)}};
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const requested=new URLSearchParams(window.location.search).get('miljo');
const initial=Object.values(meta).find(m=>m.slug===requested);
if(initial) active=Object.keys(meta).find(k=>meta[k]===initial);
renderTypes();renderArea();
